"""Governance-first institutional quantitative trading platform primitives."""


from .broker import (
    ApprovalModeService as AlphaGateXApprovalModeService,
    ApprovalStatus as AlphaGateXApprovalStatus,
    ApprovedTradePlan as AlphaGateXApprovedTradePlan,
    BrokerReconciliationService as AlphaGateXBrokerReconciliationService,
    BrokerStateSnapshot as AlphaGateXBrokerStateSnapshot,
    InstrumentResolutionStatus as AlphaGateXInstrumentResolutionStatus,
    LocalApprovalState as AlphaGateXLocalApprovalState,
    RealOrderSafetyStatus as AlphaGateXRealOrderSafetyStatus,
    SLTargetMonitor as AlphaGateXSLTargetMonitor,
    TradeApprovalRequest as AlphaGateXTradeApprovalRequest,
    ZerodhaAuthConfig as AlphaGateXZerodhaAuthConfig,
    ZerodhaAuthService as AlphaGateXZerodhaAuthService,
    ZerodhaConnectionStatus as AlphaGateXZerodhaConnectionStatus,
    ZerodhaInstrumentManager as AlphaGateXZerodhaInstrumentManager,
    ZerodhaOrderPreview as AlphaGateXZerodhaOrderPreview,
    ZerodhaOrderSafetyWrapper as AlphaGateXZerodhaOrderSafetyWrapper,
    ZerodhaWebSocketMarketDataAdapter as AlphaGateXZerodhaWebSocketMarketDataAdapter,
)
from .alpha_gate_x_indicators import (
    ConfidenceGrade as AlphaGateXConfidenceGrade,
    IndicatorContext as AlphaGateXIndicatorContext,
    IndicatorSignalComposer as AlphaGateXIndicatorSignalComposer,
    IndicatorSignalOutput as AlphaGateXIndicatorSignalOutput,
    TradingProfile as AlphaGateXTradingProfile,
)
from .alpha_gate_x import (
    AlphaGateXEngine,
    AlphaGateXSettings,
    AlphaGateXSignal,
    AlphaSignal as AlphaGateXDecision,
    DuplicateOrderGuard,
    FactorScores,
    MarketRegime as AlphaGateXMarketRegime,
    OrderRequest as AlphaGateXOrderRequest,
    OrderResult as AlphaGateXOrderResult,
    OrderRouter as AlphaGateXOrderRouter,
    OrderState as AlphaGateXOrderState,
    OrderStateMachine as AlphaGateXOrderStateMachine,
    PaperBroker as AlphaGateXPaperBroker,
    PositionSizer as AlphaGateXPositionSizer,
    RiskConfig as AlphaGateXRiskConfig,
    RiskContext as AlphaGateXRiskContext,
    RiskDecision as AlphaGateXRiskDecision,
    RiskGate as AlphaGateXRiskGate,
    RiskStatus as AlphaGateXRiskStatus,
    TradingMode as AlphaGateXTradingMode,
)
from .aegis_platform import (
    AegisQuantPlatform,
    DATA_UNAVAILABLE,
    NO_TRADE,
    ForecastEngine,
    OptionIntelligenceInput,
    OptionsIntelligenceEngine,
    PhaseResult,
    Provenance,
    Regime,
    RiskEngine,
    SignalQualityEngine,
    SignalQualityOutput,
    TradeDecision,
    ValidationFramework,
    ValidationStatus,
)
from .alpha import (
    AlphaSignal,
    alpha_diversification,
    alpha_ensemble,
    alpha_half_life,
    alternative_data_alpha,
    combinatorial_purged_cv,
    cross_asset_alpha,
    event_driven_alpha,
    ic_decay,
    information_coefficient,
    mean_reversion_alpha,
    momentum_alpha,
    options_alpha,
    purged_k_fold_splits,
    statistical_arbitrage_alpha,
    trend_following_alpha,
    volatility_alpha,
    walk_forward_splits,
)
from .data_engineering import (
    DataContract,
    DataField,
    DataQualityReport,
    DataType,
    DatasetRecord,
    FeatureRecord,
    MetadataCatalog,
    feature_mean,
    population_stability_index,
)
from .derivatives import (
    DATA_UNAVAILABLE as OptionsDataUnavailable,
    ExpiryRiskReport,
    FNOOptionContract,
    FORiskLimits,
    FORiskReport,
    GapRiskReport,
    Greeks,
    IVAnalysis,
    IVRegime,
    OptionChainAnalytics,
    OptionChainRow,
    OptionContract,
    OptionMoneyness,
    OptionPosition,
    OptionType,
    OptionsRiskEvidence,
    PortfolioGreeksReport,
    PositionGreeks,
    VolatilitySurface,
    aggregate_portfolio_greeks,
    analyze_expiry_risk,
    analyze_gap_risk,
    analyze_implied_volatility,
    analyze_option_chain,
    assess_fo_risk,
    black_scholes_price,
    calibrate_surface,
    classify_option_moneyness,
    compute_position_greeks,
    gamma_exposure,
    greeks,
    options_risk_evidence_section,
    variance_swap_fair_strike,
    volatility_forecast,
)
from .domain import AssetClass, Instrument, MarketBar, OrderBookLevel, OrderBookSnapshot, Venue
from .indicators import (
    IndicatorResult as AlphaGateXIndicatorResult,
    MarketBreadthSnapshot as AlphaGateXMarketBreadthSnapshot,
    TrendRegimeLabel as AlphaGateXTrendRegimeLabel,
    atr as alpha_gate_x_atr,
    atr_stop_loss as alpha_gate_x_atr_stop_loss,
    atr_targets as alpha_gate_x_atr_targets,
    expected_move as alpha_gate_x_expected_move,
    liquidity_sweep_score as alpha_gate_x_liquidity_sweep_score,
    market_breadth_score as alpha_gate_x_market_breadth_score,
    order_book_imbalance_score as alpha_gate_x_order_book_imbalance_score,
    trend_regime as alpha_gate_x_trend_regime,
    volume_confirmation_score as alpha_gate_x_volume_confirmation_score,
    vwap_pressure_score as alpha_gate_x_vwap_pressure_score,
)
from .execution_simulation import (
    DepthLevel,
    ExecutionMode,
    ExecutionQualityReport,
    ExecutionSimulationConfig,
    ExecutionSimulationRequest,
    ExecutionSimulator,
    LatencyBucket,
    LatencyModel,
    LatencyReport,
    MarketImpactReport,
    OrderBookSnapshot as ExecutionOrderBookSnapshot,
    SimulatedOrderType,
    SlippageAssumptions,
    SlippageReport,
    calculate_slippage,
    estimate_market_impact,
    execution_realism_evidence_section,
    round_to_tick,
)
from .execution import (
    ChildOrder,
    ExecutionPolicy,
    KillSwitchState,
    OrderIntent,
    OrderManager,
    OrderSide,
    OrderType,
    adaptive_execution_style,
    iceberg_schedule,
    order_from_signal,
    participation_schedule,
    twap_schedule,
    validate_order_intent,
    vwap_schedule,
)
from .market_data_spine import (
    BacktestConfig as AlphaGateXBacktestConfig,
    BacktestEngine as AlphaGateXBacktestEngine,
    BacktestMetrics as AlphaGateXBacktestMetrics,
    BacktestResult as AlphaGateXBacktestResult,
    CandleBuilder as AlphaGateXCandleBuilder,
    CandleTimeframe as AlphaGateXCandleTimeframe,
    DataQualityChecker as AlphaGateXDataQualityChecker,
    DataQualityReport as AlphaGateXDataQualityReport,
    DataQualityStatus as AlphaGateXDataQualityStatus,
    HistoricalDataLoader as AlphaGateXHistoricalDataLoader,
    HistoricalDataResult as AlphaGateXHistoricalDataResult,
    MarketDepth as AlphaGateXMarketDepth,
    OHLCVCandle as AlphaGateXOHLCVCandle,
    Quote as AlphaGateXQuote,
    Tick as AlphaGateXTick,
    TradeRecord as AlphaGateXTradeRecord,
    UnavailableHistoricalDataLoader as AlphaGateXUnavailableHistoricalDataLoader,
    completed_candles_for_signal as alpha_gate_x_completed_candles_for_signal,
    risk_decision_from_data_quality as alpha_gate_x_risk_decision_from_data_quality,
)
from .paper_trading import (
    ClosedPaperPosition as AlphaGateXClosedPaperPosition,
    PaperBroker as AlphaGateXRuntimePaperBroker,
    PaperFill as AlphaGateXPaperFill,
    PaperOrder as AlphaGateXPaperOrder,
    PaperOrderResult as AlphaGateXPaperOrderResult,
    PaperOrderType as AlphaGateXPaperOrderType,
    PaperPortfolio as AlphaGateXPaperPortfolio,
    PaperPosition as AlphaGateXPaperPosition,
    PaperRiskMonitor as AlphaGateXPaperRiskMonitor,
)
from .runtime import (
    AlertManager as AlphaGateXAlertManager,
    AlertType as AlphaGateXAlertType,
    DashboardSummaryService as AlphaGateXDashboardSummaryService,
    EventBus as AlphaGateXEventBus,
    InMemoryAuditStore as AlphaGateXInMemoryAuditStore,
    LivePaperRuntimeReport as AlphaGateXLivePaperRuntimeReport,
    LivePaperTradingEngine as AlphaGateXLivePaperTradingEngine,
    ReadOnlyRuntimeAPI as AlphaGateXReadOnlyRuntimeAPI,
    CrashRecoveryService as AlphaGateXCrashRecoveryService,
    ProductionRuntimeConfig as AlphaGateXProductionRuntimeConfig,
    HealthCheckService as AlphaGateXHealthCheckService,
    PersistentEventBus as AlphaGateXPersistentEventBus,
    RuntimeConfig as AlphaGateXRuntimeConfig,
    RuntimeStateSnapshot as AlphaGateXRuntimeStateSnapshot,
    RuntimeEvent as AlphaGateXRuntimeEvent,
    RuntimeEventType as AlphaGateXRuntimeEventType,
    RuntimeRecommendation as AlphaGateXRuntimeRecommendation,
    SessionManager as AlphaGateXSessionManager,
    ShadowRunGateConfig as AlphaGateXShadowRunGateConfig,
    ShadowRunRecommendation as AlphaGateXShadowRunRecommendation,
    ShadowRunValidator as AlphaGateXShadowRunValidator,
    SQLiteAuditStore as AlphaGateXSQLiteAuditStore,
    RuntimeMetrics as AlphaGateXRuntimeMetrics,
    StructuredLogger as AlphaGateXStructuredLogger,
    SessionState as AlphaGateXSessionState,
    AlertRouter as AlphaGateXAlertRouter,
    IncidentManager as AlphaGateXIncidentManager,
    IncidentSeverity as AlphaGateXIncidentSeverity,
    IncidentStatus as AlphaGateXIncidentStatus,
    MetricsRegistry as AlphaGateXMetricsRegistry,
    SLOStatus as AlphaGateXSLOStatus,
    SLOTracker as AlphaGateXSLOTracker,
    ComplianceChecklistReport as AlphaGateXComplianceChecklistReport,
    ComplianceEngine as AlphaGateXComplianceEngine,
    ComplianceRecommendation as AlphaGateXComplianceRecommendation,
    FourEyesControl as AlphaGateXFourEyesControl,
    GovernanceAction as AlphaGateXGovernanceAction,
    GovernanceEvent as AlphaGateXGovernanceEvent,
    GovernancePermission as AlphaGateXGovernancePermission,
    GovernanceRole as AlphaGateXGovernanceRole,
    GovernanceSeverity as AlphaGateXGovernanceSeverity,
    PolicyEngine as AlphaGateXPolicyEngine,
    PolicyViolation as AlphaGateXPolicyViolation,
    RoleBasedAccessControl as AlphaGateXRoleBasedAccessControl,
    TamperEvidentAuditChain as AlphaGateXTamperEvidentAuditChain,
    CertificationArea as AlphaGateXCertificationArea,
    CertificationAreaReport as AlphaGateXCertificationAreaReport,
    CertificationRecommendation as AlphaGateXCertificationRecommendation,
    CertificationScorecard as AlphaGateXCertificationScorecard,
    CertificationStatus as AlphaGateXCertificationStatus,
    EvidenceQualityReport as AlphaGateXEvidenceQualityReport,
    EvidenceQualityValidator as AlphaGateXEvidenceQualityValidator,
    FinalCertificationFramework as AlphaGateXFinalCertificationFramework,
    FinalOperationalChecklist as AlphaGateXFinalOperationalChecklist,
    FinalReadinessReport as AlphaGateXFinalReadinessReport,
    FinalReadinessReporter as AlphaGateXFinalReadinessReporter,
    ManualCertificationPackageGenerator as AlphaGateXManualCertificationPackageGenerator,
    ReviewBoard as AlphaGateXReviewBoard,
    ReviewBoardRole as AlphaGateXReviewBoardRole,
    ReviewStageStatus as AlphaGateXReviewStageStatus,
    TradingDeskWorkflow as AlphaGateXTradingDeskWorkflow,
    final_certification_evidence_section as alpha_gate_x_final_certification_evidence_section,
    BackupManager as AlphaGateXBackupManager,
    BackupMetadata as AlphaGateXBackupMetadata,
    BackupRetentionManager as AlphaGateXBackupRetentionManager,
    BackupStatus as AlphaGateXBackupStatus,
    BackupType as AlphaGateXBackupType,
    BackupVerificationReport as AlphaGateXBackupVerificationReport,
    BusinessContinuityReport as AlphaGateXBusinessContinuityReport,
    BusinessContinuityReporter as AlphaGateXBusinessContinuityReporter,
    BusinessContinuityRecommendation as AlphaGateXBusinessContinuityRecommendation,
    DisasterRecoveryReport as AlphaGateXDisasterRecoveryReport,
    DisasterRecoverySimulator as AlphaGateXDisasterRecoverySimulator,
    DisasterScenario as AlphaGateXDisasterScenario,
    HAHealthStatus as AlphaGateXHAHealthStatus,
    HAState as AlphaGateXHAState,
    RecoveryReadinessReport as AlphaGateXRecoveryReadinessReport,
    RecoveryReadinessRecommendation as AlphaGateXRecoveryReadinessRecommendation,
    RecoveryReadinessValidator as AlphaGateXRecoveryReadinessValidator,
    RestoreManager as AlphaGateXRestoreManager,
    RestoreReport as AlphaGateXRestoreReport,
    RetentionComplianceReport as AlphaGateXRetentionComplianceReport,
    RetentionPolicy as AlphaGateXRetentionPolicy,
    ha_disaster_recovery_evidence_section as alpha_gate_x_ha_disaster_recovery_evidence_section,
)
from .meta_decision import MetaDecisionEngine, MetaDecisionInput, ModelSignal
from .microstructure import (
    FootprintBar,
    auction_market_bias,
    average_trade_size,
    footprint_delta,
    liquidity_sweep_score,
    microprice,
    order_flow_imbalance,
    point_of_control,
    volume_profile,
    vpin,
)
from .ml_ai import (
    KnowledgeGraphEdge,
    ModelFamily,
    ModelPrediction,
    ModelRecord,
    ModelRegistry,
    bayesian_averaging,
    causal_effect,
    confidence_calibration,
    dynamic_ensemble_weighting,
    earnings_surprise_score,
    feature_attribution,
    filing_risk_score,
    model_blending,
    model_stacking,
    news_intelligence_score,
    probabilistic_forecast,
    research_summary_score,
)
from .observability import AuditEvent, HealthCheck, Severity, SystemHealth
from .portfolio import (
    PortfolioAllocation,
    PortfolioConstructionEngine,
    PortfolioConstructionResult,
    PortfolioPosition,
    PortfolioRiskLimits,
    PortfolioRiskReport,
    PortfolioSignalAllocation,
    PositionSizingRequest,
    PositionSizingResult,
    black_litterman_weights,
    capacity_constrained_allocation,
    cvar_optimization_weights,
    equal_risk_contribution_weights,
    hierarchical_risk_parity_weights,
    inverse_volatility_weights,
    kelly_fraction,
    mean_variance_weights,
    portfolio_expected_return,
    portfolio_var_cvar_pct,
    portfolio_volatility,
    realized_correlation,
    rebalance_trades,
    robust_optimization_weights,
    volatility_targeted_position_size,
)
from .regime import (
    RegimeLabel,
    RegimeState,
    bayesian_regime_update,
    crisis_detection,
    dynamic_regime_weighting,
    liquidity_regime,
    markov_switching_probabilities,
    online_regime_detection,
    realized_volatility,
    volatility_regime,
)
from .risk import (
    annualized_sharpe,
    conditional_value_at_risk,
    correlation_shock_loss,
    dynamic_conditional_value_at_risk,
    dynamic_value_at_risk,
    fractional_kelly,
    liquidity_shock,
    margin_forecast,
    stress_test_loss,
    value_at_risk,
    volatility_shock_loss,
)
from .research import (
    ApprovalStatus,
    BacktestRecord,
    ExperimentRun,
    ReproducibilityManifest,
    ResearchAuditEvent,
    ResearchNotebook,
    ResearchRegistry,
)
from .research_ml import (
    BaselineComparison as AlphaGateXResearchBaselineComparison,
    ExperimentTracker as AlphaGateXExperimentTracker,
    FeatureAvailabilityStatus as AlphaGateXFeatureAvailabilityStatus,
    MLValidationGate as AlphaGateXMLValidationGate,
    MLValidationGateResult as AlphaGateXMLValidationGateResult,
    ModelRiskReport as AlphaGateXModelRiskReport,
    ModelRiskReporter as AlphaGateXModelRiskReporter,
    OfflineFeatureStore as AlphaGateXOfflineFeatureStore,
    OfflineModelEvaluator as AlphaGateXOfflineModelEvaluator,
    ResearchDataset as AlphaGateXResearchDataset,
    ResearchDatasetBuilder as AlphaGateXResearchDatasetBuilder,
    ResearchDatasetRow as AlphaGateXResearchDatasetRow,
    ResearchExperimentRecord as AlphaGateXResearchExperimentRecord,
    ResearchFeatureRecord as AlphaGateXResearchFeatureRecord,
    ResearchMLReport as AlphaGateXResearchMLReport,
    ResearchRecommendation as AlphaGateXResearchRecommendation,
    ResearchReportGenerator as AlphaGateXResearchReportGenerator,
    advisory_ml_decision as alpha_gate_x_advisory_ml_decision,
    research_ml_evidence_section as alpha_gate_x_research_ml_evidence_section,
)
from .signal_engine import (
    ApprovalGate,
    FinalSignalEngine,
    MarketDecision,
    SignalInput,
    SignalOutput,
)
from .validation import (
    GoLiveGateConfig as AlphaGateXGoLiveGateConfig,
    GoLiveGateResult as AlphaGateXGoLiveGateResult,
    PerformanceMetrics as AlphaGateXPerformanceMetrics,
    RobustnessRecommendation as AlphaGateXRobustnessRecommendation,
    RobustnessReport as AlphaGateXRobustnessReport,
    RobustnessScorecard as AlphaGateXRobustnessScorecard,
    RobustnessValidationInput as AlphaGateXRobustnessValidationInput,
    RiskEventRecord as AlphaGateXRiskEventRecord,
    RiskReport as AlphaGateXRiskReport,
    StrategyRobustnessValidator as AlphaGateXStrategyRobustnessValidator,
    ValidationReport as AlphaGateXValidationReport,
    WalkForwardResult as AlphaGateXWalkForwardResult,
    analyze_by_regime as alpha_gate_x_analyze_by_regime,
    analyze_by_symbol as alpha_gate_x_analyze_by_symbol,
    analyze_by_time as alpha_gate_x_analyze_by_time,
    build_equity_curve as alpha_gate_x_build_equity_curve,
    build_risk_report as alpha_gate_x_build_risk_report,
    calculate_performance_metrics as alpha_gate_x_calculate_performance_metrics,
    create_validation_report as alpha_gate_x_create_validation_report,
    equity_curve_to_csv as alpha_gate_x_equity_curve_to_csv,
    evaluate_go_live_gate as alpha_gate_x_evaluate_go_live_gate,
    report_to_json as alpha_gate_x_report_to_json,
    report_to_markdown as alpha_gate_x_report_to_markdown,
    run_walk_forward as alpha_gate_x_run_walk_forward,
    trades_to_csv as alpha_gate_x_trades_to_csv,
    walk_forward_splits as alpha_gate_x_walk_forward_splits,
)
from .strategy_orchestration import (
    AllocationMethod,
    CapitalAllocationEngine,
    ConflictResolutionReport,
    StrategyAllocationReport,
    StrategyCorrelationAnalyzer,
    StrategyCorrelationReport,
    StrategyHealthScore,
    StrategyHealthScorer,
    StrategyHealthStatus,
    StrategyMetadata,
    StrategyPerformanceTracker,
    StrategyRegime,
    StrategyRegimeCompatibility,
    StrategyRegistry,
    StrategyRiskProfile,
    StrategySignal,
    UnifiedSignalAggregator,
    UnifiedSignalDecision,
    multi_strategy_evidence_section,
    regime_compatibility,
)
from .tca_governance import (
    Fill,
    GovernanceDecision,
    TCASummary,
    automated_retraining_decision,
    average_fill_price,
    benchmark_slippage,
    concept_drift_detection,
    implementation_shortfall,
    market_impact_attribution,
    model_risk_score,
    pre_trade_compliance,
    reconciliation_breaks,
    resilience_recovery_point,
    surveillance_score,
    tca_summary,
    twap_benchmark,
    vwap_benchmark,
)
from .tiers import PlatformTier, TierCatalog, build_v8_tier_catalog

__all__ = [
    "DepthLevel",
    "ExecutionMode",
    "ExecutionQualityReport",
    "ExecutionSimulationConfig",
    "ExecutionSimulationRequest",
    "ExecutionSimulator",
    "LatencyBucket",
    "LatencyModel",
    "LatencyReport",
    "MarketImpactReport",
    "ExecutionOrderBookSnapshot",
    "SimulatedOrderType",
    "SlippageAssumptions",
    "SlippageReport",
    "calculate_slippage",
    "estimate_market_impact",
    "execution_realism_evidence_section",
    "round_to_tick",
    "ExpiryRiskReport",
    "FNOOptionContract",
    "FORiskLimits",
    "FORiskReport",
    "GapRiskReport",
    "IVAnalysis",
    "IVRegime",
    "OptionChainAnalytics",
    "OptionChainRow",
    "OptionMoneyness",
    "OptionPosition",
    "OptionsDataUnavailable",
    "OptionsRiskEvidence",
    "PortfolioGreeksReport",
    "PositionGreeks",
    "aggregate_portfolio_greeks",
    "analyze_expiry_risk",
    "analyze_gap_risk",
    "analyze_implied_volatility",
    "analyze_option_chain",
    "assess_fo_risk",
    "classify_option_moneyness",
    "compute_position_greeks",
    "options_risk_evidence_section",
    "AllocationMethod",
    "CapitalAllocationEngine",
    "ConflictResolutionReport",
    "StrategyAllocationReport",
    "StrategyCorrelationAnalyzer",
    "StrategyCorrelationReport",
    "StrategyHealthScore",
    "StrategyHealthScorer",
    "StrategyHealthStatus",
    "StrategyMetadata",
    "StrategyPerformanceTracker",
    "StrategyRegime",
    "StrategyRegimeCompatibility",
    "StrategyRegistry",
    "StrategyRiskProfile",
    "StrategySignal",
    "UnifiedSignalAggregator",
    "UnifiedSignalDecision",
    "multi_strategy_evidence_section",
    "regime_compatibility",
    "PortfolioAllocation",
    "PortfolioConstructionEngine",
    "PortfolioConstructionResult",
    "PortfolioPosition",
    "PortfolioRiskLimits",
    "PortfolioRiskReport",
    "PortfolioSignalAllocation",
    "kelly_fraction",
    "portfolio_var_cvar_pct",
    "portfolio_volatility",
    "AlphaGateXGoLiveGateConfig",
    "AlphaGateXGoLiveGateResult",
    "AlphaGateXPerformanceMetrics",
    "AlphaGateXRiskEventRecord",
    "AlphaGateXRiskReport",
    "AlphaGateXRobustnessRecommendation",
    "AlphaGateXRobustnessReport",
    "AlphaGateXRobustnessScorecard",
    "AlphaGateXRobustnessValidationInput",
    "AlphaGateXStrategyRobustnessValidator",
    "AlphaGateXValidationReport",
    "AlphaGateXWalkForwardResult",
    "alpha_gate_x_analyze_by_regime",
    "alpha_gate_x_analyze_by_symbol",
    "alpha_gate_x_analyze_by_time",
    "alpha_gate_x_build_equity_curve",
    "alpha_gate_x_build_risk_report",
    "alpha_gate_x_calculate_performance_metrics",
    "alpha_gate_x_create_validation_report",
    "alpha_gate_x_equity_curve_to_csv",
    "alpha_gate_x_evaluate_go_live_gate",
    "alpha_gate_x_report_to_json",
    "alpha_gate_x_report_to_markdown",
    "alpha_gate_x_run_walk_forward",
    "alpha_gate_x_trades_to_csv",
    "alpha_gate_x_walk_forward_splits",
    "AlphaGateXConfidenceGrade",
    "AlphaGateXIndicatorContext",
    "AlphaGateXIndicatorSignalComposer",
    "AlphaGateXIndicatorSignalOutput",
    "AlphaGateXTradingProfile",
    "AlphaGateXIndicatorResult",
    "AlphaGateXMarketBreadthSnapshot",
    "AlphaGateXTrendRegimeLabel",
    "alpha_gate_x_atr",
    "alpha_gate_x_atr_stop_loss",
    "alpha_gate_x_atr_targets",
    "alpha_gate_x_expected_move",
    "alpha_gate_x_liquidity_sweep_score",
    "alpha_gate_x_market_breadth_score",
    "alpha_gate_x_order_book_imbalance_score",
    "alpha_gate_x_trend_regime",
    "alpha_gate_x_volume_confirmation_score",
    "alpha_gate_x_vwap_pressure_score",
    "AlphaGateXBacktestConfig",
    "AlphaGateXBacktestEngine",
    "AlphaGateXBacktestMetrics",
    "AlphaGateXBacktestResult",
    "AlphaGateXCandleBuilder",
    "AlphaGateXCandleTimeframe",
    "AlphaGateXDataQualityChecker",
    "AlphaGateXDataQualityReport",
    "AlphaGateXDataQualityStatus",
    "AlphaGateXHistoricalDataLoader",
    "AlphaGateXHistoricalDataResult",
    "AlphaGateXMarketDepth",
    "AlphaGateXOHLCVCandle",
    "AlphaGateXQuote",
    "AlphaGateXTick",
    "AlphaGateXTradeRecord",
    "AlphaGateXUnavailableHistoricalDataLoader",
    "alpha_gate_x_completed_candles_for_signal",
    "alpha_gate_x_risk_decision_from_data_quality",
    "AlphaGateXEngine",
    "AlphaGateXSettings",
    "AlphaGateXSignal",
    "AlphaGateXDecision",
    "DuplicateOrderGuard",
    "FactorScores",
    "AlphaGateXMarketRegime",
    "AlphaGateXOrderRequest",
    "AlphaGateXOrderResult",
    "AlphaGateXOrderRouter",
    "AlphaGateXOrderState",
    "AlphaGateXOrderStateMachine",
    "AlphaGateXPaperBroker",
    "AlphaGateXPositionSizer",
    "AlphaGateXRiskConfig",
    "AlphaGateXRiskContext",
    "AlphaGateXRiskDecision",
    "AlphaGateXRiskGate",
    "AlphaGateXRiskStatus",
    "AlphaGateXTradingMode",
    "AegisQuantPlatform",
    "DATA_UNAVAILABLE",
    "NO_TRADE",
    "ForecastEngine",
    "OptionIntelligenceInput",
    "OptionsIntelligenceEngine",
    "PhaseResult",
    "Provenance",
    "Regime",
    "RiskEngine",
    "SignalQualityEngine",
    "SignalQualityOutput",
    "TradeDecision",
    "ValidationFramework",
    "ValidationStatus",
    "ApprovalGate",
    "AssetClass",
    "AuditEvent",
    "DataContract",
    "DataField",
    "DataQualityReport",
    "DataType",
    "DatasetRecord",
    "ExecutionPolicy",
    "FeatureRecord",
    "FinalSignalEngine",
    "HealthCheck",
    "Instrument",
    "KillSwitchState",
    "MarketBar",
    "MarketDecision",
    "MetadataCatalog",
    "OrderBookLevel",
    "ExecutionOrderBookSnapshot",
    "OrderIntent",
    "OrderSide",
    "OrderType",
    "PlatformTier",
    "PositionSizingRequest",
    "PositionSizingResult",
    "Severity",
    "SignalInput",
    "SignalOutput",
    "SystemHealth",
    "TierCatalog",
    "Venue",
    "build_v8_tier_catalog",
    "equal_risk_contribution_weights",
    "feature_mean",
    "inverse_volatility_weights",
    "order_from_signal",
    "population_stability_index",
    "portfolio_expected_return",
    "realized_correlation",
    "rebalance_trades",
    "validate_order_intent",
    "volatility_targeted_position_size",
    "AlphaSignal",
    "ApprovalStatus",
    "BacktestRecord",
    "ChildOrder",
    "ExperimentRun",
    "FootprintBar",
    "GovernanceDecision",
    "Greeks",
    "KnowledgeGraphEdge",
    "MetaDecisionEngine",
    "MetaDecisionInput",
    "ModelFamily",
    "ModelPrediction",
    "ModelRecord",
    "ModelRegistry",
    "ModelSignal",
    "OptionContract",
    "OptionType",
    "OrderManager",
    "RegimeLabel",
    "RegimeState",
    "ReproducibilityManifest",
    "ResearchAuditEvent",
    "ResearchNotebook",
    "ResearchRegistry",
    "TCASummary",
    "VolatilitySurface",
    "adaptive_execution_style",
    "alpha_diversification",
    "alpha_ensemble",
    "alpha_half_life",
    "alternative_data_alpha",
    "auction_market_bias",
    "average_trade_size",
    "bayesian_averaging",
    "bayesian_regime_update",
    "black_scholes_price",
    "calibrate_surface",
    "causal_effect",
    "combinatorial_purged_cv",
    "confidence_calibration",
    "crisis_detection",
    "cross_asset_alpha",
    "dynamic_ensemble_weighting",
    "dynamic_regime_weighting",
    "earnings_surprise_score",
    "event_driven_alpha",
    "feature_attribution",
    "filing_risk_score",
    "footprint_delta",
    "gamma_exposure",
    "greeks",
    "ic_decay",
    "iceberg_schedule",
    "information_coefficient",
    "liquidity_regime",
    "liquidity_sweep_score",
    "markov_switching_probabilities",
    "mean_reversion_alpha",
    "microprice",
    "model_blending",
    "model_stacking",
    "momentum_alpha",
    "news_intelligence_score",
    "online_regime_detection",
    "options_alpha",
    "order_flow_imbalance",
    "participation_schedule",
    "point_of_control",
    "probabilistic_forecast",
    "purged_k_fold_splits",
    "realized_volatility",
    "research_summary_score",
    "statistical_arbitrage_alpha",
    "trend_following_alpha",
    "twap_schedule",
    "variance_swap_fair_strike",
    "volatility_alpha",
    "volatility_forecast",
    "volatility_regime",
    "volume_profile",
    "vpin",
    "vwap_schedule",
    "walk_forward_splits",
    "Fill",
    "automated_retraining_decision",
    "average_fill_price",
    "benchmark_slippage",
    "concept_drift_detection",
    "implementation_shortfall",
    "market_impact_attribution",
    "model_risk_score",
    "pre_trade_compliance",
    "reconciliation_breaks",
    "resilience_recovery_point",
    "surveillance_score",
    "tca_summary",
    "twap_benchmark",
    "vwap_benchmark",
    "annualized_sharpe",
    "black_litterman_weights",
    "capacity_constrained_allocation",
    "conditional_value_at_risk",
    "correlation_shock_loss",
    "cvar_optimization_weights",
    "dynamic_conditional_value_at_risk",
    "dynamic_value_at_risk",
    "fractional_kelly",
    "hierarchical_risk_parity_weights",
    "liquidity_shock",
    "margin_forecast",
    "mean_variance_weights",
    "robust_optimization_weights",
    "stress_test_loss",
    "value_at_risk",
    "volatility_shock_loss",
    "AlphaGateXResearchBaselineComparison",
    "AlphaGateXExperimentTracker",
    "AlphaGateXFeatureAvailabilityStatus",
    "AlphaGateXMLValidationGate",
    "AlphaGateXMLValidationGateResult",
    "AlphaGateXModelRiskReport",
    "AlphaGateXModelRiskReporter",
    "AlphaGateXOfflineFeatureStore",
    "AlphaGateXOfflineModelEvaluator",
    "AlphaGateXResearchDataset",
    "AlphaGateXResearchDatasetBuilder",
    "AlphaGateXResearchDatasetRow",
    "AlphaGateXResearchExperimentRecord",
    "AlphaGateXResearchFeatureRecord",
    "AlphaGateXResearchMLReport",
    "AlphaGateXResearchRecommendation",
    "AlphaGateXResearchReportGenerator",
    "alpha_gate_x_advisory_ml_decision",
    "alpha_gate_x_research_ml_evidence_section",
    "AlphaGateXAlertRouter",
    "AlphaGateXIncidentManager",
    "AlphaGateXIncidentSeverity",
    "AlphaGateXIncidentStatus",
    "AlphaGateXMetricsRegistry",
    "AlphaGateXSLOStatus",
    "AlphaGateXSLOTracker",
    "AlphaGateXComplianceChecklistReport",
    "AlphaGateXComplianceEngine",
    "AlphaGateXComplianceRecommendation",
    "AlphaGateXFourEyesControl",
    "AlphaGateXGovernanceAction",
    "AlphaGateXGovernanceEvent",
    "AlphaGateXGovernancePermission",
    "AlphaGateXGovernanceRole",
    "AlphaGateXGovernanceSeverity",
    "AlphaGateXPolicyEngine",
    "AlphaGateXPolicyViolation",
    "AlphaGateXRoleBasedAccessControl",
    "AlphaGateXTamperEvidentAuditChain",
    "AlphaGateXCertificationArea",
    "AlphaGateXCertificationAreaReport",
    "AlphaGateXCertificationRecommendation",
    "AlphaGateXCertificationScorecard",
    "AlphaGateXCertificationStatus",
    "AlphaGateXEvidenceQualityReport",
    "AlphaGateXEvidenceQualityValidator",
    "AlphaGateXFinalCertificationFramework",
    "AlphaGateXFinalOperationalChecklist",
    "AlphaGateXFinalReadinessReport",
    "AlphaGateXFinalReadinessReporter",
    "AlphaGateXManualCertificationPackageGenerator",
    "AlphaGateXReviewBoard",
    "AlphaGateXReviewBoardRole",
    "AlphaGateXReviewStageStatus",
    "AlphaGateXTradingDeskWorkflow",
    "alpha_gate_x_final_certification_evidence_section",
    "AlphaGateXBackupManager",
    "AlphaGateXBackupMetadata",
    "AlphaGateXBackupRetentionManager",
    "AlphaGateXBackupStatus",
    "AlphaGateXBackupType",
    "AlphaGateXBackupVerificationReport",
    "AlphaGateXBusinessContinuityReport",
    "AlphaGateXBusinessContinuityReporter",
    "AlphaGateXBusinessContinuityRecommendation",
    "AlphaGateXDisasterRecoveryReport",
    "AlphaGateXDisasterRecoverySimulator",
    "AlphaGateXDisasterScenario",
    "AlphaGateXHAHealthStatus",
    "AlphaGateXHAState",
    "AlphaGateXRecoveryReadinessReport",
    "AlphaGateXRecoveryReadinessRecommendation",
    "AlphaGateXRecoveryReadinessValidator",
    "AlphaGateXRestoreManager",
    "AlphaGateXRestoreReport",
    "AlphaGateXRetentionComplianceReport",
    "AlphaGateXRetentionPolicy",
    "alpha_gate_x_ha_disaster_recovery_evidence_section",
]
